export function BattlesController() {
  const results = [
    {
      round: 1,
      attacker_id: 2,
      defender_id: 1,
      dmg: 165,
      remainedHP: 1035,
      criticalHIT: false,
      block: false,
    },
    {
      round: 2,
      attacker_id: 2,
      defender_id: 1,
      dmg: 112,
      remainedHP: 923,
      criticalHIT: false,
      block: false,
    },
    {
      round: 3,
      attacker_id: 2,
      defender_id: 1,
      dmg: 55,
      remainedHP: 868,
      criticalHIT: false,
      block: false,
    },
    {
      round: 4,
      attacker_id: 2,
      defender_id: 1,
      dmg: 79,
      remainedHP: 789,
      criticalHIT: false,
      block: false,
    },
    {
      round: 5,
      attacker_id: 2,
      defender_id: 1,
      dmg: 68,
      remainedHP: 721,
      criticalHIT: false,
      block: false,
    },
    {
      round: 6,
      attacker_id: 2,
      defender_id: 1,
      dmg: 82,
      remainedHP: 639,
      criticalHIT: false,
      block: false,
    },
    {
      round: 7,
      attacker_id: 2,
      defender_id: 1,
      dmg: 158,
      remainedHP: 481,
      criticalHIT: false,
      block: false,
    },
    {
      round: 8,
      attacker_id: 2,
      defender_id: 1,
      dmg: 71,
      remainedHP: 410,
      criticalHIT: false,
      block: false,
    },
    {
      round: 9,
      attacker_id: 2,
      defender_id: 1,
      dmg: 148,
      remainedHP: 262,
      criticalHIT: false,
      block: false,
    },
    {
      round: 10,
      attacker_id: 2,
      defender_id: 1,
      dmg: 121,
      remainedHP: 141,
      criticalHIT: false,
      block: false,
    },
    {
      round: 11,
      attacker_id: 2,
      defender_id: 1,
      dmg: 72,
      remainedHP: 69,
      criticalHIT: false,
      block: false,
    },
    {
      round: 12,
      attacker_id: 2,
      defender_id: 1,
      dmg: 167,
      remainedHP: 0,
      criticalHIT: false,
      block: false,
      dead: true,
    },
  ];

  return {
    results,
  };
}
